name: Docker Build and Deploy

on:
  push:
    branches:
      - master
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-apache-app .

    - name: Run Docker container
      run: docker run -d -p 80:80 my-apache-app

    - name: Delay for container startup
      run: sleep 10

    - name: Get homepage
      run: |
        mkdir -p artifacts
        curl -o artifacts/homepage.html http://localhost

    - name: Create artifact
      run: tar -czvf artifacts.tar.gz artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifacts.tar.gz
